title:            Robbie Mackay
description:      'Software Developer and Eco Geek, Works for Ushahidi'
#logo:             site-logo.png
logo:
disqus_shortname: robbiemackay
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://robbiemackay.com
#url:              http://localhost:4000

# Owner/author information
owner:
  name:           Robbie Mackay
  avatar:         2014_HeadshotRobbieMackay_150p.jpg
  email:          rm@robbiemackay.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        rjmackay
  facebook:
  github:         rjmackay
  stackexchange:
  linkedin:       rjmackay
  instagram:
  flickr:         rjmackay
  tumblr:
  feedburner :    RobbieMackay
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-15623315-2
google_analytics_domain: robbiemackay.com
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Work
    url: /resume/
  - title: Articles
    url: /articles/
  - title: TIL
    url: /learned/
#  - title: Made Mistakes
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Pacific/Auckland
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title/
permalink:   /:categories/:year/:month/:day/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

prose :
  metadata:
    "": |
      layout: page
      title: ""
      tagline: ""
    "_posts": |
      layout: post
      title:    ""
      tagline:  ""
      published: false
      hidden: false


exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
