---
label: Default
hide_body: false
fields:
- type: text
  label: Title
  name: title
  description: Page Title
  config:
    required: true
- name: date
  type: datetime
  label: Date
  config:
    required: true
- name: author
  type: text
  label: Author
  default: Robbie Mackay
  config:
    required: false
- name: tags
  type: tag_list
  label: Tags
- name: categories
  type: tag_list
  label: Categories
pages:
- _posts/2019-03-28-this-week.md
- _posts/building-a-progressive-web-app.md
- _posts/questions-i-wish-people-asked-in-an-interview.md
- _posts/2017-05-18-a-little-less-coffee.md
- _posts/2017-04-23-adding-optional-parameters-in-lumen-routes.md
- _posts/2017-04-26-why-i-run.md
- _posts/2017-05-18-psychological-safety.md
